### ISSUE TITLE
Guacamole: xRDP is not keyboard-agnostic

### ISSUE THREAD

**Issue by awalende** [deNBI/resenvs#147]
When configuring guacamole with xrdp (as this role does), user are not able to use various keys or shortcut keys.
German Keyboard user are not able to type special chars like ö,ä,ü since rdp does not recognize them.
Also special chars like | or other are not usable.

Possible solution:

Add multiple connections in `user-mapping.xml.j2` with different `server-layout` like for example:

```
        <connection name="Ubuntu Server (German Keyboard Layout)">
                <protocol>rdp</protocol>
                <param name="hostname">127.0.0.1</param>
                <param name="port">3389</param>
                <param name="server-layout">de-de-qwertz</param>
        </connection>

        <connection name="Ubuntu Server (US Keyboard Layout)">
                <protocol>rdp</protocol>
                <param name="hostname">127.0.0.1</param>
                <param name="port">3389</param>
                <param name="server-layout">en-us-qwerty</param>
        </connection>
```

User then have to chose the right connection suiting their keyboard layout. This also needs documentation:
![Screenshot_20221128_161826](https://user-images.githubusercontent.com/20296419/204314276-6b833ea5-6e59-4a8f-9187-e1c5646036e5.png)

The issue is explained in the guacamole docs:
https://guacamole.apache.org/doc/gug/configuring-guacamole.html#session-settings

**Comment by dweinholz** [comment]
Thank you , has now been adjusted.
